// CallTree types — transcribed verbatim from calltree-api-contract.md §2.
// Keep this file in sync with the contract; it is the single source of truth
// for the shapes the backend serves.

export type Id = string;

// ---------- Persisted entities ----------
export interface Company {
  id: Id;
  name: string;
  buyers: Buyer[];
  /** Prospect context — varies per company; optional so older data still loads. */
  industry?: string;
  seats?: number;
  /** The tool the prospect currently uses that Slack would displace. */
  incumbent?: string;
}
export interface Buyer {
  id: Id;
  name: string;
  title: string;
  /** Buyer archetype the AI plays in practice. Synthetic now; LLM-derived from the
   *  transcript later. References a persona id from GET /personas. */
  personaId?: Id;
}
export interface Salesperson {
  id: Id;
  name: string;
}

export interface Call {
  id: Id;
  companyId: Id;
  salespersonId: Id;
  buyerId: Id;
  startedAt: string; // ISO 8601
  treeId: Id;
  recordingIds: Id[];
}

export interface Tree {
  id: Id;
  callId: Id;
  rootNodeId: Id;
  nodes: TreeNode[];
}

export interface TreeNode {
  id: Id;
  parentId: Id | null;
  childIds: Id[];
  title: string; // "Pushback"
  description: string; // "You don't have Tableau integration"
  speaker: "seller" | "buyer";
  tMs: number; // offset into the call this moment occurred
  successProbability: number; // 0..1   → green↔red spectrum
  expectedValue: number; // currency
  metrics: SignalMetrics;
  stats?: NodeStats; // optional — observed traversal stats across this call's population
}

/** Beta-smoothed win statistics observed across the call population. */
export interface NodeStats {
  visits: number;
  wins: number;
  winRate: number; // (wins + 1) / (visits + 2)
}

export interface SignalMetrics {
  confidence: number;
  hesitation: number;
  enthusiasm: number;
} // each 0..1

export interface Recording {
  id: Id;
  callId: Id;
  treeId: Id;
  isReal: boolean; // true = actual call; false = a mock
  isActive: boolean; // currently in progress (live)
  startNodeId: Id | null; // mock: where practice begins (null = root)
  stopNodeId: Id | null; // mock: breakpoint to stop at
  audioPath: string;
  lengthMs: number;
  transcript: TranscriptSegment[];
  traversal: Traversal;
  aiNotes: AssistCard | null; // live intel — latest per-turn assist card
  aiFeedback: AiFeedback | null; // post-call review
}

export interface TranscriptSegment {
  index: number;
  speaker: "seller" | "buyer";
  text: string;
  tStartMs: number;
  tEndMs: number;
}
export interface Traversal {
  initialNodeId: Id;
  finalNodeId: Id;
  steps: TraversalStep[];
}
export interface TraversalStep {
  transcriptIndex: number;
  fromNodeId: Id;
  toNodeId: Id;
  tMs: number;
}

export interface AiNotes {
  commitments: string[];
  objections: string[];
  facts: string[];
  suggestions: string[];
}

/** Per-turn seller assist card generated by GPT with optional web search. */
export interface AssistCard {
  /** The buyer utterance that triggered this card. */
  triggerText: string;
  /** GPT's concise response — shown verbatim in the seller overlay. */
  response: string;
  /** True when GPT used the web_search_preview tool to produce this response. */
  searchedWeb: boolean;
}
export interface PracticeTarget {
  nodeId: Id;
  reason: string;
  drill: string;
  metric: keyof SignalMetrics;
  score: number;
}
export interface AiFeedback {
  summary: string;
  strengths: string[];
  weaknesses: string[];
  practiceTargets: PracticeTarget[];
  /** Top "start practicing here" pick (System 2) — cites in-call signal + history. */
  recommendedStart?: {
    nodeId: Id;
    /** Plain-language title of the moment (humanized; falls back to the node title). */
    heading?: string;
    reason: string;
    /** LLM-written rationale; may contain [n] markers into citations. */
    description?: string;
    /** Short bullet lines (plain language, **bold** + [n] markers). Preferred over description. */
    reasons?: string[];
    citations?: Citation[];
  };
}

/**
 * A real, hoverable citation: the exact transcript moment where a rep played a
 * sub-optimal move on an actual call. `[n]` markers in insight text resolve here.
 */
export interface Citation {
  id: number; // the [n] number
  callId: Id;
  company: string;
  buyer: { name: string; title: string };
  outcome: "won" | "lost" | "open";
  nodeId: Id;
  nodeTitle: string;
  takenTitle: string; // the move they played
  betterTitle: string; // the higher-win sibling move
  winTaken: number; // 0..1 (Beta-smoothed)
  winBest: number; // 0..1 (Beta-smoothed)
  takenWins: number; // observed real counts (wins of visits) for plain "X of Y times" copy
  takenVisits: number;
  bestWins: number;
  bestVisits: number;
  evGap: number;
  quote: string; // exact transcript line at the taken node
}

// ---------- Derived / transport (not persisted) ----------
export interface CallSummary {
  id: Id;
  company: string;
  industry?: string; // prospect context, resolved from the call's company
  seats?: number;
  incumbent?: string;
  startedAt: string;
  outcome: "won" | "lost" | "open"; // kept for internal use; UI shows the evaluation
  bestEV: number; // max node EV in the tree
  finalEV: number; // EV at the node the real call ended on (realized value)
  buyer: { name: string; title: string; personaId?: Id }; // resolved from the call's buyerId
  salesperson: { id: Id; name: string }; // resolved from the call's salespersonId
}
export interface CallDetail {
  call: Call;
  tree: Tree;
  recordings: Recording[];
  /** Resolved buyer for this call, incl. the auto-assigned practice persona. */
  buyer?: { name: string; title: string; personaId?: Id };
}
export interface TimelineCue {
  atMs: number;
  nodeId: Id;
}
/** A single node's TTS clip — the per-node bundle used for exact, gapless sync. */
export interface WalkthroughSegment {
  nodeId: Id;
  audioUrl: string;
}
export interface WalkthroughBundle {
  audioUrl: string; // single concatenated render (fallback playback)
  timeline: TimelineCue[]; // cue offsets into audioUrl (fallback sync)
  segments?: WalkthroughSegment[]; // one clip per path node → exact, gapless sync
}

/** One persona the AI buyer can play (GET /personas). */
export interface PersonaInfo {
  id: Id;
  name: string;
  description: string;
}

/** GET /salespeople → rep list for the practice picker (winRate 0..1). */
export interface SalespersonListItem {
  id: Id;
  name: string;
  totalCalls: number;
  winRate: number;
}

/**
 * GET /salespeople/:id/recommended-practice — the single "perfect practice call"
 * for one rep, derived from their baseline stats. reasons[] cite REAL numbers.
 */
export interface RecommendedPractice {
  salespersonId: Id;
  salespersonName: string;
  callId: Id;
  treeId: Id;
  startNodeId: Id;
  startNodeTitle: string;
  personaId: Id;
  personaName: string;
  headline: string;
  /** Reason lines; may contain [n] markers that resolve into `citations`. */
  reasons: string[];
  /** Real-quote evidence behind the reasons (hoverable [n] refs). */
  citations?: Citation[];
  /** The recommended call, so the UI can show its card. */
  call?: CallSummary;
}

/** GET /admin/status — when insights were last regenerated. */
export interface AdminStatus {
  generatedAt: string | null;
  usedLLM: boolean;
}

/** The cached insight bundle (backend/src/data/insights.json). */
export interface InsightsBundle {
  generatedAt: string;
  usedLLM: boolean;
  salespersonId: Id;
  perfectPractice: RecommendedPractice;
  /** Per-call recommended-start override, keyed by callId. */
  perCall: Record<Id, NonNullable<AiFeedback["recommendedStart"]>>;
}

/** A skill verdict for a single mock call, from the analysis LLM. */
export interface MockSkillTag {
  category: string;
  passed: boolean;
}

/** POST /recordings/:id/mock-analysis result — drives the post-call popup. */
export interface MockCallAnalysis {
  summary: string; // 2-3 sentences
  topStrength: string;
  topWeakness: string;
  comparisonLine: string; // single "vs how you usually do" line, built in code
  outcome: "won" | "lost" | "open";
  skillTags: MockSkillTag[]; // only skills that actually came up
  salespersonName: string;
}

export type LiveEvent =
  | { type: "transcript"; segment: TranscriptSegment }
  | { type: "move"; step: TraversalStep; node: TreeNode }
  | { type: "branch"; node: TreeNode }
  | { type: "metrics"; nodeId: Id; metrics: SignalMetrics }
  | { type: "notes"; card: AssistCard };

// ---------- Request bodies ----------
export interface StartRecordingReq {
  callId: Id;
  isReal: boolean;
  startNodeId?: Id;
  stopNodeId?: Id;
}
export interface AppendReq {
  segments: TranscriptSegment[];
  steps?: TraversalStep[];
}
export interface BranchReq {
  recordingId: Id;
  currentNodeId: Id;
  utterance: string;
}
export interface MockTurnReq {
  recordingId: Id;
  role: "buyer" | "seller" | "both";
  currentNodeId: Id;
}
export interface NotesReq {
  window: TranscriptSegment[];
}
export interface TtsReq {
  text: string;
  voiceId: string;
}
export interface CreateCallReq {
  companyId: Id;
  salespersonId: Id;
  buyerId: Id;
  startedAt: string;
  audioPath?: string;
}
export interface MockAnalysisReq {
  personaId: Id;
}

// Shape of the seed JSON store.
export interface SeedStore {
  _meta: { note: string; dealValue: number };
  companies: Company[];
  salespeople: Salesperson[];
  calls: Call[];
  trees: Record<Id, Tree>;
  recordings: Record<Id, Recording>;
}
