// AUTO-GENERATED by seed/build.ts — DO NOT EDIT BY HAND.
// Run `npm run seed` (from backend/) to regenerate. Source: seed/calltree.seed.ts.
// Node ids match the backend seed exactly, so every node is Simulatable/Watchable.
import type { RawNode, Actor } from "../components/tree/treeData";

export const GEN_TREE: RawNode = {
  "id": "n_open",
  "kind": "real",
  "title": "Warm opening",
  "description": "Thanks for taking the time to chat today, Sarah — I’m excited to discuss how Slack can help your team.",
  "onPath": true,
  "children": [
    {
      "id": "n_disc",
      "kind": "real",
      "title": "Discovery",
      "description": "Can you share how your team communicates and collaborates using Microsoft Teams right now?",
      "onPath": true,
      "children": [
        {
          "id": "n_incumbent",
          "kind": "real",
          "title": "Incumbent objection",
          "description": "We already use Microsoft Teams — it's bundled with our license.",
          "onPath": true,
          "children": [
            {
              "id": "n_coexist",
              "kind": "ai",
              "title": "Reframe",
              "description": "Actually, Slack can run alongside Teams; it’s designed to complement your existing tools, not replace them.",
              "success": 0.76,
              "children": [
                {
                  "id": "n_curious",
                  "kind": "ai",
                  "title": "Curious buyer",
                  "description": "Okay, but where does Slack actually win over Teams?",
                  "success": 0.95,
                  "children": [
                    {
                      "id": "n_pilot",
                      "kind": "ai",
                      "title": "Pilot offer",
                      "description": "How about we set up a low-risk 2-week pilot with one of your teams to see how it goes?",
                      "success": 0.95,
                      "children": [
                        {
                          "id": "n_yes",
                          "kind": "ai",
                          "title": "Pilot agreement",
                          "description": "Sure, let’s run the pilot and see how it works out.",
                          "success": 0.95
                        }
                      ]
                    }
                  ]
                },
                {
                  "id": "n_unconvinced",
                  "kind": "ai",
                  "title": "Pushback",
                  "description": "We just standardized on Teams — not now.",
                  "success": 0.08
                }
              ]
            },
            {
              "id": "n_discover",
              "kind": "ai",
              "title": "Discovery-first",
              "description": "What aspects of Teams do you find most challenging in your day-to-day operations?",
              "success": 0.9,
              "children": [
                {
                  "id": "n_pain",
                  "kind": "ai",
                  "title": "Admitting pain",
                  "description": "Honestly, the search functionality is weak and threads often get lost.",
                  "success": 0.9,
                  "children": [
                    {
                      "id": "n_show",
                      "kind": "ai",
                      "title": "Show solution",
                      "description": "Slack’s powerful search and organized threads can really address those pain points — would you like to see a demo?",
                      "success": 0.9,
                      "children": [
                        {
                          "id": "n_demo",
                          "kind": "ai",
                          "title": "Demo booked",
                          "description": "Yes, let’s schedule a demo to explore this further.",
                          "success": 0.9
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "id": "n_knock",
              "kind": "real",
              "title": "Disparaging Teams",
              "description": "I think Teams is a bit clunky and outdated — it really struggles with user experience.",
              "onPath": true,
              "children": [
                {
                  "id": "n_defensive",
                  "kind": "real",
                  "title": "Defensive response",
                  "description": "Just send me some info, please.",
                  "onPath": true
                }
              ]
            }
          ]
        },
        {
          "id": "n_price",
          "kind": "ai",
          "title": "Cost inquiry",
          "description": "What does this run for 250 people?",
          "success": 0.45,
          "children": [
            {
              "id": "n_value",
              "kind": "ai",
              "title": "Value anchoring",
              "description": "Let’s focus on the value — think about the time saved per seat rather than just the sticker price.",
              "success": 0.67,
              "children": [
                {
                  "id": "n_proof",
                  "kind": "ai",
                  "title": "Proof request",
                  "description": "Can you show me proof that it pays off at our size?",
                  "success": 0.91,
                  "children": [
                    {
                      "id": "n_caseclose",
                      "kind": "ai",
                      "title": "Case study success",
                      "description": "That case study is really relevant — I’m ready to move forward.",
                      "success": 0.91
                    }
                  ]
                },
                {
                  "id": "n_pushprice",
                  "kind": "ai",
                  "title": "Price balking",
                  "description": "I’m still not sure about the price.",
                  "success": 0.08
                }
              ]
            },
            {
              "id": "n_discount",
              "kind": "ai",
              "title": "Discount lead",
              "description": "We can offer you a discount to make this more appealing.",
              "success": 0.11,
              "children": [
                {
                  "id": "n_anchor",
                  "kind": "ai",
                  "title": "Anchoring low",
                  "description": "I was hoping for something even lower than that.",
                  "success": 0.12
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};

export const GEN_ACTOR: Record<string, Actor> = {
  "n_open": "seller",
  "n_disc": "seller",
  "n_incumbent": "buyer",
  "n_coexist": "seller",
  "n_curious": "buyer",
  "n_pilot": "seller",
  "n_yes": "buyer",
  "n_unconvinced": "buyer",
  "n_discover": "seller",
  "n_pain": "buyer",
  "n_show": "seller",
  "n_demo": "buyer",
  "n_knock": "seller",
  "n_defensive": "buyer",
  "n_price": "buyer",
  "n_value": "seller",
  "n_proof": "buyer",
  "n_caseclose": "buyer",
  "n_pushprice": "buyer",
  "n_discount": "seller",
  "n_anchor": "buyer"
};
