// AUTO-GENERATED by seed/build.ts — DO NOT EDIT BY HAND.
// Run `npm run seed` (from backend/) to regenerate. Source: seed/calltree.seed.ts.
// Node ids match the backend seed exactly, so every node is Simulatable/Watchable.
import type { RawNode, Actor } from "../components/tree/treeData";

export const GEN_TREE: RawNode = {
  "id": "n_open",
  "kind": "real",
  "title": "Opening",
  "description": "Set the agenda",
  "onPath": true,
  "visits": 100,
  "winRate": 0.61,
  "children": [
    {
      "id": "n_disc",
      "kind": "real",
      "title": "Discovery",
      "description": "How does your team chat today?",
      "onPath": true,
      "visits": 100,
      "winRate": 0.61,
      "children": [
        {
          "id": "n_incumbent",
          "kind": "real",
          "title": "Incumbent",
          "description": "We already use Microsoft Teams",
          "onPath": true,
          "visits": 67,
          "winRate": 0.7,
          "children": [
            {
              "id": "n_coexist",
              "kind": "real",
              "title": "Coexist",
              "description": "Runs alongside Microsoft Teams",
              "onPath": true,
              "visits": 41,
              "winRate": 0.79,
              "children": [
                {
                  "id": "n_curious",
                  "kind": "real",
                  "title": "Curious",
                  "description": "Where does Slack win?",
                  "onPath": true,
                  "visits": 33,
                  "winRate": 0.97,
                  "children": [
                    {
                      "id": "n_pilot",
                      "kind": "real",
                      "title": "Pilot Offer",
                      "description": "Offer a 2-week pilot",
                      "onPath": true,
                      "visits": 33,
                      "winRate": 0.97,
                      "children": [
                        {
                          "id": "n_yes",
                          "kind": "real",
                          "title": "Pilot Won",
                          "description": "Let's run the pilot",
                          "onPath": true,
                          "visits": 33,
                          "winRate": 0.97
                        }
                      ]
                    }
                  ]
                },
                {
                  "id": "n_unconvinced",
                  "kind": "ai",
                  "title": "Pushback",
                  "description": "We just standardized on Microsoft Teams",
                  "success": 0.08,
                  "visits": 8,
                  "winRate": 0.1
                }
              ]
            },
            {
              "id": "n_discover",
              "kind": "ai",
              "title": "Find Pain",
              "description": "What's painful about Microsoft Teams?",
              "success": 0.94,
              "visits": 14,
              "winRate": 0.94,
              "children": [
                {
                  "id": "n_pain",
                  "kind": "ai",
                  "title": "Pain Found",
                  "description": "Search is weak, threads get lost",
                  "success": 0.94,
                  "visits": 14,
                  "winRate": 0.94,
                  "children": [
                    {
                      "id": "n_show",
                      "kind": "ai",
                      "title": "Show Fit",
                      "description": "Pitch search + threads",
                      "success": 0.94,
                      "visits": 14,
                      "winRate": 0.94,
                      "children": [
                        {
                          "id": "n_demo",
                          "kind": "ai",
                          "title": "Demo Booked",
                          "description": "Book me a demo",
                          "success": 0.94,
                          "visits": 14,
                          "winRate": 0.94
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "id": "n_knock",
              "kind": "ai",
              "title": "Knock Incumbent",
              "description": "Knock Microsoft Teams as clunky",
              "success": 0.07,
              "visits": 12,
              "winRate": 0.07,
              "children": [
                {
                  "id": "n_defensive",
                  "kind": "ai",
                  "title": "Defensive",
                  "description": "Just send me some info",
                  "success": 0.07,
                  "visits": 12,
                  "winRate": 0.07
                }
              ]
            }
          ]
        },
        {
          "id": "n_price",
          "kind": "ai",
          "title": "Price Ask",
          "description": "What's this run for 250?",
          "success": 0.43,
          "visits": 33,
          "winRate": 0.43,
          "children": [
            {
              "id": "n_value",
              "kind": "ai",
              "title": "Anchor Value",
              "description": "Anchor on value per seat",
              "success": 0.65,
              "visits": 21,
              "winRate": 0.65,
              "children": [
                {
                  "id": "n_proof",
                  "kind": "ai",
                  "title": "Proof Ask",
                  "description": "Prove it pays off at our size",
                  "success": 0.94,
                  "visits": 14,
                  "winRate": 0.94,
                  "children": [
                    {
                      "id": "n_caseclose",
                      "kind": "ai",
                      "title": "Case Closes",
                      "description": "That case study sells me",
                      "success": 0.94,
                      "visits": 14,
                      "winRate": 0.94
                    }
                  ]
                },
                {
                  "id": "n_pushprice",
                  "kind": "ai",
                  "title": "Too Pricey",
                  "description": "Still too expensive",
                  "success": 0.08,
                  "visits": 7,
                  "winRate": 0.11
                }
              ]
            },
            {
              "id": "n_discount",
              "kind": "ai",
              "title": "Discount",
              "description": "Lead with a discount",
              "success": 0.07,
              "visits": 12,
              "winRate": 0.07,
              "children": [
                {
                  "id": "n_anchor",
                  "kind": "ai",
                  "title": "Anchored Low",
                  "description": "Can you go lower?",
                  "success": 0.18,
                  "visits": 12,
                  "winRate": 0.07
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};

export const GEN_ACTOR: Record<string, Actor> = {
  "n_open": "seller",
  "n_disc": "seller",
  "n_incumbent": "buyer",
  "n_coexist": "seller",
  "n_curious": "buyer",
  "n_pilot": "seller",
  "n_yes": "buyer",
  "n_unconvinced": "buyer",
  "n_discover": "seller",
  "n_pain": "buyer",
  "n_show": "seller",
  "n_demo": "buyer",
  "n_knock": "seller",
  "n_defensive": "buyer",
  "n_price": "buyer",
  "n_value": "seller",
  "n_proof": "buyer",
  "n_caseclose": "buyer",
  "n_pushprice": "buyer",
  "n_discount": "seller",
  "n_anchor": "buyer"
};
